// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebLottery.Infrastructure.Implementations.DataContext;

#nullable disable

namespace WebLottery.Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("currency_sequence")
                .HasMin(1L)
                .HasMax(999999L);

            modelBuilder.HasSequence<int>("draw_sequence")
                .HasMin(1L)
                .HasMax(999999L);

            modelBuilder.HasSequence<int>("pocket_sequence")
                .HasMin(1L)
                .HasMax(9999999L);

            modelBuilder.HasSequence<int>("pocket_ticket_sequence")
                .HasMin(1L)
                .HasMax(999999L);

            modelBuilder.HasSequence<int>("prize_sequence")
                .HasMin(1L)
                .HasMax(999999L);

            modelBuilder.HasSequence<int>("ticket_sequence")
                .HasMin(1L)
                .HasMax(9999999L);

            modelBuilder.HasSequence<int>("user_sequence")
                .HasMin(1L)
                .HasMax(999999L);

            modelBuilder.HasSequence<int>("wallet_currency_sequence")
                .HasMin(1L)
                .HasMax(999999L);

            modelBuilder.HasSequence<int>("wallet_sequence")
                .HasMin(1L)
                .HasMax(999999L);

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Currency.CurrencyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"currency_sequence\"')");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("abbreviation");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCreated")
                        .HasColumnType("integer");

                    b.Property<int>("UserUpdated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Draw.DrawEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"draw_sequence\"')");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentAmountPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("cur_am_players");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnded")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAmountPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_am_players");

                    b.Property<int>("PrizeId")
                        .HasColumnType("integer")
                        .HasColumnName("prize_id");

                    b.Property<int>("TicketPrice")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCreated")
                        .HasColumnType("integer");

                    b.Property<int>("UserUpdated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("draw", (string)null);
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Pocket.PocketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"pocket_sequence\"')");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCreated")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("UserUpdated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("pocket", (string)null);
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.PocketTicket.PocketTicketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"pocket_ticket_sequence\"')");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("PocketEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("PocketId")
                        .HasColumnType("integer")
                        .HasColumnName("pocket_id");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCreated")
                        .HasColumnType("integer");

                    b.Property<int>("UserUpdated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PocketEntityId");

                    b.ToTable("pocket_ticket", (string)null);
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Prize.PrizeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"prize_sequence\"')");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrencyEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCreated")
                        .HasColumnType("integer");

                    b.Property<int>("UserUpdated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyEntityId");

                    b.ToTable("prize", (string)null);
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Ticket.TicketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"ticket_sequence\"')");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DrawEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("DrawId")
                        .HasColumnType("integer")
                        .HasColumnName("draw_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LuckyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("lucky_number");

                    b.Property<DateTime>("PurchaseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCreated")
                        .HasColumnType("integer");

                    b.Property<int>("UserUpdated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DrawEntityId");

                    b.ToTable("ticket", (string)null);
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.User.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"user_sequence\"')");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCreated")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.Property<int>("UserUpdated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Wallet.WalletEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"wallet_sequence\"')");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCreated")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("UserUpdated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("wallet", (string)null);
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.WalletCurrency.WalletCurrencyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"wallet_currency_sequence\"')");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrencyEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("column_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCreated")
                        .HasColumnType("integer");

                    b.Property<int>("UserUpdated")
                        .HasColumnType("integer");

                    b.Property<int?>("WalletEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyEntityId");

                    b.HasIndex("WalletEntityId");

                    b.ToTable("wallet_currency", (string)null);
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Pocket.PocketEntity", b =>
                {
                    b.HasOne("WebLottery.Infrastructure.Entities.User.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.PocketTicket.PocketTicketEntity", b =>
                {
                    b.HasOne("WebLottery.Infrastructure.Entities.Pocket.PocketEntity", null)
                        .WithMany("PocketTickets")
                        .HasForeignKey("PocketEntityId");
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Prize.PrizeEntity", b =>
                {
                    b.HasOne("WebLottery.Infrastructure.Entities.Currency.CurrencyEntity", null)
                        .WithMany("Prizes")
                        .HasForeignKey("CurrencyEntityId");
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Ticket.TicketEntity", b =>
                {
                    b.HasOne("WebLottery.Infrastructure.Entities.Draw.DrawEntity", null)
                        .WithMany("Tickets")
                        .HasForeignKey("DrawEntityId");
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.WalletCurrency.WalletCurrencyEntity", b =>
                {
                    b.HasOne("WebLottery.Infrastructure.Entities.Currency.CurrencyEntity", null)
                        .WithMany("WalletCurrencies")
                        .HasForeignKey("CurrencyEntityId");

                    b.HasOne("WebLottery.Infrastructure.Entities.Wallet.WalletEntity", null)
                        .WithMany("WalletCurrencies")
                        .HasForeignKey("WalletEntityId");
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Currency.CurrencyEntity", b =>
                {
                    b.Navigation("Prizes");

                    b.Navigation("WalletCurrencies");
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Draw.DrawEntity", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Pocket.PocketEntity", b =>
                {
                    b.Navigation("PocketTickets");
                });

            modelBuilder.Entity("WebLottery.Infrastructure.Entities.Wallet.WalletEntity", b =>
                {
                    b.Navigation("WalletCurrencies");
                });
#pragma warning restore 612, 618
        }
    }
}
